service: mamao

provider:
  name: aws
  runtime: nodejs18.x
  stage: development
  region: sa-east-1
  memorySize: 256
  timeout: 30

functions:
  mamao:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-apigw-binary
  - serverless-dotenv-plugin

custom:
  apigwBinary:
    types:
      - 'image/*'
  dotenv:
    exclude:
      - AWS_REGION
